### ISSUE TITLE
Rephrase the first sentence of this block?

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/ietf-cesr-proof#13]
https://github.com/WebOfTrust/ietf-cesr-proof/blob/main/draft-pfeairheller-cesr-proof.md#nested-partial-signatures

CESR Proof Signatures can be used to sign as many portions of a SAD (including the entire SAD) whether the signed subsets are SADs or the self-addressing identifer (SAID) of a SAD. 

CESR Proof Signatures can be used to sign as many portions (or 'subsets') of a SAD as needed, including the entire SAD. The signed subsets are either SADs themselves or the multisig part of the / one or more* self-addressing identifers (SAID) of Self Addressing Data (SAD). 

* I don't have clue, what it needs to be, but you get the idea: pls use shorter sentences and write the concept out a bit more for better understanding ;)

**Comment by pfeairheller** [comment]
Closed with PR #19
