### ISSUE TITLE
An infographic would help

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/ietf-cesr-proof#14]
https://github.com/WebOfTrust/ietf-cesr-proof/blob/main/draft-pfeairheller-cesr-proof.md#transposable-signature-attachments

a drawing maybe says more than the words in this text block?

**Comment by pfeairheller** [comment]
I do not believe infographics are allowed in IETF specs.  And I would know what a drawing of this would look like.

**Comment by henkvancann** [comment]
I do not believe infographics are allowed in IETF specs -> Fair enough. 

And I would know what a drawing of this would look like ->
Am I correct with this sketch? In this example Sig A of Payload in envelop A is transposed. Pls correct me if I am wrong.

![signal-2022-01-05-222406](https://user-images.githubusercontent.com/479356/148291726-c7837b1c-04f2-4fcb-a687-bfc295d53eb5.jpeg)

**Comment by henkvancann** [comment]
<img width="875" alt="Transposable Signature Attachments" src="https://user-images.githubusercontent.com/479356/150328656-63310bd8-6ce2-4f47-b9f9-20b0d39c05db.png">
