### ISSUE TITLE
SAD path language sounds like marketing?

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/ietf-cesr-proof#15]
"This path language has a more limited scope than alternatives like JSONPtr [RFC6901] or JSONPath [JSONPath] and is therefore simpler and more compact when encoding in CESR signature attachments. SADs in CESR and therefore CESR Proof Signatures require static field ordering of all maps. The SAD path language takes advantage of this feature to allow for a base64 compatible syntax into SADs even when a SAD uses non-base64 compatible characters for field labels."

This block comes across as a clever way to sell a short-coming. 

CESR Proof Signatures require static field ordering of all maps. -> why?

"takes advantage of this feature" -> or works within the self imposed limitation?

This text block leaves question about what we throw away (e.g. extensibility?) because we're not going to create something like JSONPtr [RFC6901] or JSONPath [JSONPath].

Could you shine a light on why CESR Proof Sigs and KERI will never need the scope that the alternatives cover.

**Comment by henkvancann** [comment]
This helps already: https://github.com/WebOfTrust/ietf-cesr-proof/blob/main/draft-pfeairheller-cesr-proof.md#alternative-pathing--query-languages 

Maybe forward refer to this paragraph?

**Comment by SmithSamuelM** [comment]
Anything that must be signed must be serialized and that serialization must be reproducable.  This means the field ordering must be fixed. So its not a unique limitation. Given that we have fixed field ordering we can simplify pathing so its is win.
JSONPth and JsonPtr were intended for non-crypto graphic applicatioins where field ordering is not required to be fixed.

**Comment by henkvancann** [comment]
got it. I think it would be an improvement if your answer were added to that section.
