### ISSUE TITLE
Term 'Map' could be defined / explained better

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/ietf-cesr-proof#16]
the picture show the first occurrence of the term 'map' in https://github.com/WebOfTrust/ietf-cesr-proof/blob/main/draft-pfeairheller-cesr-proof.md#transposable-signature-attachments

<img width="1043" alt="Screenshot 2021-12-29 at 01 11 12" src="https://user-images.githubusercontent.com/479356/147616190-95ba2c5b-4f68-45a3-a00a-e510a8f6b99a.png">

Is a map the same as an envelop? 

The term 'Map' could be defined / explained better

**Comment by pfeairheller** [comment]
Ack

**Comment by pfeairheller** [comment]
Closed with PR #19
