### ISSUE TITLE
CESR encoding of SAD paths

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/ietf-cesr-proof#17]
<img width="1039" alt="Screenshot 2021-12-29 at 01 18 53" src="https://user-images.githubusercontent.com/479356/147616439-6c958f98-7d60-45c1-8677-ff05ac4609e2.png">

typo encodeing -> encoding 

Question: is this an example of the tranposibility of CESR too? 
SAD Paths in text <-> binary encoding 

Term 'T Domain' is not explained and new in this paragraph

**Comment by pfeairheller** [comment]
Fixed typo.

We can't display the path in binary here because it is, well...  binary and wouldn't display.

Added a reference to T and B for text and binary and pointed to the CESR spec.

(I'm going to close all the issues with my next PR, but commenting individually where appropriate.)

**Comment by pfeairheller** [comment]
Closed with PR #19
