### ISSUE TITLE
IANA consideration, first explain briefly what it is.

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/ietf-cesr-proof#18]
https://github.com/WebOfTrust/ietf-cesr-proof/blob/main/draft-pfeairheller-cesr-proof.md#iana-considerations

"The Internet Assigned Numbers Authority (IANA) is a standards organization that oversees global IP address allocation, autonomous system number allocation, root zone management in the Domain Name System (DNS), media types, and other Internet Protocol-related symbols and Internet numbers."
More info: https://en.wikipedia.org/wiki/Internet_Assigned_Numbers_Authority

**Comment by pfeairheller** [comment]
Closed with PR #19
